---
title: Java异常学习笔记
description: 尚硅谷版Java异常处理学习笔记
date: 2023-1-24 17:33:12
updated: 
tags:
  - Java
categories:
  - Java
cover: https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/images/AgAAC6u-TVO-6GCp-41Pb5VAdprXFwlM.png
abbrlink: 
feature: true
---
# Java异常处理

## 异常概述与异常体系结构
>在使用计算机语言进行项目开发的过程中，即使程序员把代码写得<b style="color:blue">尽善尽美</b>，在系统的运行过程中仍然会遇到一些问题，因为很多问题不是靠代码能够避免的，比如：<b style="color:red">客户输入数据的格式，读取文件是否存在，网络是否始终保持通畅</b>等等。

- 异常：在Java语言中，将程序执行中发生的不正常情况称为“异常”。（开发过程中的语法错误和逻辑错误不是异常）
- Java程序在执行过程中所发生的异常事件可分为两类：
  - <b style="color:blue">Error</b>：Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。比如：<b style="color:red">StackOverflowError</b>和<b style="color:red">OOM</b>。一般不编写针对性的代码进行处理。
  - <b style="color:blue">Exception</b>：其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如：
    ✅空指针访问
    ✅试图读取不存在的文件
    ✅网络连接中断
    ✅数组角标越界
  - 对于这些错误，一般有两种解决方法：一是遇到错误就终止程序的运行。另一种方法是由程序员在编写程序时，就考虑到错误的检测、错误消息的提示，以及错误的处理。
  - 捕获错误最理想的是在编译期间，但有的错误只有在运行时才会发生。
    比如：除数为0，数组下标越界等
    分类：编译时异常和运行时异常

![图1](https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/md-imgs/63cfb5f0588a5d166c6ca70b.png)![图2](https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/md-imgs/63cfb57d588a5d166c6bb7aa.png)

<b style="color:blue">蓝色：非受检（unchecked）异常</b>
<b style="color:red">红色：受检（checked）异常</b>

**1.运行时异常**

- 是指编译器不要求强制处置的异常。一般是指编程时的逻辑错误，是程员应该积极避免其出现的异常。<b style="color:red">java.lang.RuntimeException</b>类及它的子类都是运行时异常。
- 对于这类异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。

**2.编译时异常**

- 是指编译器要求必须处置的异常。即程序在运行时由于外界因素造成的一般性异常。<b style="color:red">编译器要求  Java程序必须捕获或声明所有编译时异常。</b>
- 对于这类异常，如果程序不处理，可能会带来意想不到的结果。

## 常见异常

- java.lang.RuntimeException
  - ClassCastException
  - ArrayindexOutOfBoundsException
  - Nul PointerException
  - ArithmeticException
  - NumberFormatException
  - InputMismatchException
- java.io.OExeption
  - FileNotFoundException
  - EOFException
- java.lang.ClassNotFoundException
- java.lang.InterruptedException
- java.io.FileNotFoundException
- java.sql.SQLException

<b style="color:red">ArraylndexOutofBoundsException</b>示例如下：
```java
public class IndexOutExp {
      public static void main(String[] args) {
            String friends[] = { "lisa", "bily","kessy" };
                  for (int i 0;ix 5;i++) {
                      System.out.println(friends[i]); // friends[4]?
                      }
                  System.out.println("\n this is the end");
      }
}
```
:::tip
程序IndexOutExp.java编译正确，运行结果：java IndexOutExp
  lisa
  bily
  kessy
  java.lang.ArraylndexOutofBoundsException
     at Test7_1.main(Test7_ 1.java:5)
  Exception in thread "main"
:::

<b style="color:red">NullPointerException</b>示例如下：

```java
public class NullRef {
    int i = 1;
    public static void main(String[] args) {
         NullRef t = new Nul1Ref();
         t = null;
         System.out. printin(t.i);
      }
}
```
:::tip
程序NulRef.java编译正确，运行结果：java NullRef
  java.lang.NullPointerException
          at NullRef.main(NullRef java:6)
  Exception in thread "main"
:::

<b style="color:red">ArithmeticException</b>示例如下：

```java
public class DivideZero {
      int x;
      public static void main (String[] args) {
      int y;
      DivideZero c=new Dividezero();
      y=3/c.x;
      System.out.println("program ends ok!");
     }
   }
```
:::tip
程序DivideZero.java编译正确，运行结果：java DivideZero
java.lang.ArithmeticException: / by zero
at DivideZero.main(DivideZero.java:6)
Exception in thread "main"
:::

<b style="color:red">ClassCastException</b>示例如下：

```java
public static void main(String[] args) {
      public class Order {
         Object obj = new Date();
         Order order;
         Order= (Order) obj;
         System.out.println(order);
    }
  }
```
:::tip
程序Personjava编译正确，运行结果：java Person
  java.lang.java.lang.ClassCastException
   at Person.main(Person.java:5)
   Exception in thread "main"
:::


## 异常处理机制一：try-catch-finally

<b style="color:blue">在编写程序时，经常要在可能出现错误的地方加上检测的代码，如进行x/y运算时，要检测分母为0，数据为空，输入的不是数据而是字符等。过多的if-else分支会导致程序的代码加长、臃肿，可读性差。因此采用异常处理机制。</b>

**Java异常处理**
Java采用的异常处理机制，是将异常处理的程序代码集中在一起，与正常的程序代码分开，使得程序简洁、优雅，并易于维护。

<b style="color:blue">Java异常处理的方式：</b>
方式一：try-catch-finally
方式二：throws+异常类型

- Java提供的是异常处理的抓抛模型。
- Java程序的执行过程中如出现异常，会生成一个异常类对象，该异常对象将被提交给Java运行时系统，这个过程称为抛出(throw)异常。
- 异常对象的生成
👉由虚拟机**自动生成**：程序运行过程中，虚拟机检测到程序发生了问题，如果在当前代码中没有找到相应的处理程序，就会在后台自动创建一个对应异常类的实例对象并抛出——自动抛出
👉由开发人员**手动创建**：`Exception exception = new ClassCastException()`;——创建好的异常对象不抛出对程序没有任何影响，和创建一个 普通对象一样

<b style="color:blue">异常的抛出机制</b>

![图3](https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/md-imgs/63cfb57d588a5d166c6bb7c8.png) 

为保证程序正常执行，代码必须对可能出现的异常进行处理。

- 如果一个方法内抛出异常，该异常对象会被抛给调用者方法中处理。如果异常没有在调用者方法中处理，它继续被抛给这个调用方法的上层方法。这个过程将一直继续下去，直到异常被处理。这一过程称为<b style="color:red">捕获(catch)异常</b>。
- 如果一个异常回到main()方法，并且main()也不处理，则程序运行终止。
- 程序员通常只能处理Exception，而对Error无能为力。

异常处理是通过ty-catch-finally语句实现的。
```java
try{
...//可能产生异常的代码
}
catch( ExceptionName1 e){
...//当产生ExceptionName1型异常时的处置措施
}catch( ExceptionName2 e){
...//当产生ExceptionName2型异常时的处置措施
}finally{
...//无论是否发生异常，都无条件执行的语句
}]
```

- try
  捕获异常的第一步是用try..}语句块选定捕获异常的范围，将可能出现异常的代码放在try语句块中。
- catch (Exceptiontype e)
在catch语句块中是对异常对象进行处理的代码。每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象。

:::tip
如果明确知道产生的是何种异常，可以用该异常类作为catch的参数；也可以用其父类作为catch的参数。
比如：可以用 ArithmeticException 类作为参数的地方，就可以用RuntimeException类作为参数，或者用所有异常的父类Exception类作为参数。但不能是与ArithmeticException类无关的异常，如NullPointerException ( catch中的语句将不会执行)。
:::

- 捕获异常的有关信息：
  与其它对象一样，可以访问一个异常对象的成员变量或调用它的方法。
    - getMessage() 获取异常信息，返回字符串
    - printStack Trace() 获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。

![图4](https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/md-imgs/63cfb57d588a5d166c6bb7ea.png)  

- finally
👉捕获异常的最后一步是通过finally语句为异常处理提供一个统一的出口，使得在控制流转到程序的其它部分以前，能够对程序的状态作统一的管理。
👉<b style="color:red">不论在try代码块中是否发生了异常事件，catch语句是否执行，catch语句是否有异常，catch语句中是否有return，finally块中的语句都会被执行。</b>
👉finally语句和catch语句是任选的。

![图5](https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/md-imgs/63cfb55a588a5d166c6b3a46.png) 

```java
public class IndexOutExp {
      public static void main(Stringt[] args) {
            String friends[] ={ "1isa","bily","kessy" };
                  try {
                      for (int i = 0; i< 5; i++) {
                         System.out.println(friends [i]);
                       }
                  } catch (ArrayIndexOutofBounds Exception e) {
                      System.out.println("index err");
                  }
                      System.out.println("\n this is the end");
                  }
                    }
```
:::tip
程序indexOutExp.java运行结果：java IndexOutExp
     lisa
     bily
     kessy
     index err
     this is the end
:::

举例：
```java
public class DivideZero1 {
        int X;
        public static void main (String[] args){
             int y;
             DivideZero1 C = new DivideZero1();
             try{
             y=3/c.x;
             } catch (ArithmeticException e) {
              System.out.println("divide by zero error!");
             }
             System. out.println("program ends ok!");
            }
          }
```
:::tip
程序DivideZero1运行结果：java Dividezero1
    divide by zero error!
    program ends ok!
:::

<b style="color:red">练习：</b>
编写一个类ExceptionTest，在main方法中使用try、catch、finally，要求：
👉在try块中，编写被零除的代码。
👉在catch块中，捕获被零除所产生的异常，并且打印异常信息
👉在finally块中，打印一条语句。

**体会**
- 捕获和不捕获异常，程序的运行有什么不同。
- 体会try语句块中可能发生多个不同异常时的处理。
- 体会finally语句块的使用。

**不捕获异常时的情况**
- 前面使用的异常都是<b style="color:red">RuntimeException</b>类或是它的子类，这些类的异常的特点是：即使没有使用**try**和**catch**捕获，**Java**自己也能捕获，并且编译通过(但运行时会发生异常使得程序运行终止)。
-如果抛出的异常是IOException等类型的非运行时异常，则<b style="color:blue">必须捕获，否则编译错误。</b>也就是说，我们必须处理编译时异常，将异常进行捕捉，转化为运行时异常

**<b style="color:blue">IOException</b>异常处理举例（1）**

```java
import java.io.*;

public class IOExp {
     public static void main(String[] args) {
         FileInputStream in=new FileInputStream ("atguigushk.txt");
         int b;
         b = in.read();
         while (b != -1) {
         System.out.print((char) b);
         b = in.read();
       }
       in.close();
     }
    }
```

**<b style="color:blue">IOException</b>异常处理举例（2）**
```java
import java.io.*;
public class IOExp {
      public static void main(String[] args) {
          try {
             FileInputStream in = new FileInputstream("atguigushk.txt");
             int b;
             b = in.read();
             while (b ！= -1){
                System.out.print((char) b);
                b = in.read();
             }
             in.close();
             } catch (IOException e) {
                System.out.println(e);
          } finally {
               System.out.println(" It's ok!");
       }
    }
}
```

**练习2 捕获和处理IOException异常**
编译、运行应用程序<b style="color:green">IOExp.java</b>，体会Java语言中异常的捕获和处理机制。相关知识：<b style="color:green">FilelnputStream</b>类的成员方法<b style="color:green">read()</b>的功能是每次从相应的(本地为ASCl码编码格式)文件中读取一个字节，并转换成0~255之间的int型整数返回，到达文件末尾时则返回-1。


## 异常处理机制二：throws

- 声明抛出异常是Java中处理异常的第二种方式
  ➡️如果一个方法(中的语句执行时）可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。
  ➡️在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。
  
- 声明抛出异常举例：
  <b style="color:red">public void readFile (String file) throws FileNotFoundException {</b>
  ...
  <b style="color:blue">// 读文件的操作可能产生FileNotFoundException类型的异常</b>
  <b style="color:green">FilelnputStream fis = new FilelnputStream(file);</b>
  ...}       

举例：

```java
import java.io.*;
       public class ThrowsTest {
             public static void main(String[] args) {
                     ThrowsTest t =new ThrowsTest();
                      try {
                           t.readFile();
                      }catch (I0Exception e) {
                           e.printStackTrace();
                        }
             }
             public void readFile() throws IOException{ //throws：抛出IO异常
                     FileInputStream in = new FileInputstream("atguigushk.txt");
                     int b;
                     b = in.read()；
                     while (b != -1) {
                         System.out.print( (char) b);
                         b= in.read();
                       }
                       in.close();
             }
       }
```

![图6](https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/md-imgs/63cfb55a588a5d166c6b3a5c.png) 


**重写方法声明抛出异常的原则**
重写方法不能抛出比被重写方法范围更大的异常类型。在多态的情况下，对methodA()方法的调用-异常的捕获按父类声明的异常处理。

<b style="color:red">public class A{</b>
<b style="color:red">public void methodA() throws <b style="color:blue">IOException</b> {</b>
<b style="color:red">. . .</b>
<b style="color:red">}}</b>
<b style="color:red">public class B1 extends A{</b>
  <b style="color:red">public void methodA() throws <b style="color:blue">FileNotFoundException</b>{</b>
   <b style="color:red">. . .</b>
<b style="color:red">}}</b>
<b style="color:red">public class B2 extends A{</b>
   <b style="color:red">public void methodA() throws <b style="color:blue">Exception</b> { //报错</b>
   <b style="color:red">. . .</b>
<b style="color:red">}}</b>

## 手动抛出异常：throw

Java异常类对象除在程序执行过程中出现异常时由系统自动生成并抛出，也可根据需要使用人工创建并抛出。
➡️首先要生成异常类对象，然后通过throw语句实现抛出操作(提交给Java运行环境)。
<b style="color:red">IOException e = new IOException();</b>
<b style="color:red">throw e;</b>
➡️可以抛出的异常必须是 Throwable或其子类的实例。下面的语句在编译时将会产生语法错误：
<b style="color:red">throw new String("want to throw");</b>

## 用户自定义异常类

- 一般地，用户自定义异常类都是`RuntimeException`的子类。
- 自定义异常类通常需要编写几个重载的构造器。
- 自定义异常需要提供`serialVersionUI`。
- 自定义的异常通过`throw抛出`。
- 自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型。

用户自定义异常类MyException，用于描述数据取值范围错误信息。用户自己的异常类<b style="color:red">必须继承</b>现有的异常类。

例一：
```java
class MyException extends Exception {
      static final long serialVersionUID = 13465653435L;
      private int idnumber;
      public MyException(String message, int id) {
           super (message);
           this.idnumber= id;
       }
      public int getId() {
           return idnumber;
      }
  }
```
例二：

```java
public class MyExpTest{
      public void regist(int num) throws MyException {
           if(num < 0)
           throw new MyException("人数为负值，不合理"，3);
           else
               System.out.println("登记人数"+ num);
       }
       public void manager() {
            try {
               regist(100);
            } catch (MyException e) {
               System.out.print（"登记失败，出错种类"+ e.getId());
               }
                System.out.print("本次登记操作结束");
              }
public static void main(String args[]){
           MyExpTest t = new MyExpTest();
           t.manager();
           } 
         }
```

**总结：异常处理5个关键字**

![图7](https://yimoorua-img.oss-cn-chengdu.aliyuncs.com/md-imgs/63cfb55b588a5d166c6b3a92.png) 

